# Generated by Django 2.0.3 on 2018-03-24 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SlugField(max_length=64, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id',
                 models.SlugField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.SlugField(max_length=11, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('thumbnail', models.URLField(verbose_name='Thumbnail url')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Room'),
        ),
    ]
